### PR TITLE
remove libsass from dependencies, add Django 2.0 to tests

### LINKED ISSUE #77: Suggestion: remove libsass from install_requires
Hi

The module docs say libsass is not required in production but the module declares it as its dependency.

I'm using pip-tools and the presence of libsass in setup.py makes it end up in my requirements.txt. This in turn means my dev env has to have buildtools (gcc, etc) installed.
This is inconvenient as I'm using docker and want my image to be as small as possible.

Should libsass be removed from setup.py as the docs already mention it has to be installed manually when needed?

### PR DESCRIPTION
**Pull request by emirotin**
Fixes #77

I've verified it with my project (using as `-e` dependency) and all looks good.
I'm also using Django 2.0 and things work so I think you can test against this version.

### CODE REVIEW

**Comment by AndreasBackx** [comment]
LGTM, weird that the builds aren't starting. Travis is/was having a problem I guess?

**Comment by emirotin** [comment]
"Waiting to be queued", looks legit

**Comment by jrief** [comment]
@emirotin 
I restarted the job, now it passes for Django-1.11, but 2.0 complains with
```
AttributeError: 'module' object has no attribute 'lru_cache'
```

**Comment by emirotin** [comment]
Oh I see, Django 2.0 doesn't work on Py 2.7, we need to more accurately define the combinations, it's not the fully rectangular matrix anymore.

File: README.md [hunk 1]
```diff
@@ -11,32 +11,30 @@ third party services nor special IDE plugins.
 [![PyPI](https://img.shields.io/pypi/l/django-sass-processor.svg)]()
 [![Twitter Follow](https://img.shields.io/twitter/follow/shields_io.svg?style=social&label=Follow&maxAge=2592000)](https://twitter.com/jacobrief)
 
-**django-sass-processor** converts ``*.scss`` or ``*.sass`` files into ``*.css`` while rendering
+**django-sass-processor** converts `*.scss` or `*.sass` files into `*.css` while rendering
```
Comment (emirotin) [inline README.md]: Note: markdown changes were auto-made by my editor's Prettier plugin when I've added the changelog entry. Can revert if you wish.

**Comment by emirotin** [comment]
I've implemented the change, now the failing combination is excluded but Travis is hanging again.

**Comment by jrief** [comment]
thanks @emirotin

**Comment by emirotin** [comment]
Thank you. Was the new version published?

**Comment by emirotin** [comment]
Ping: can you please publish the newest version?
